version = 3
final_space = true

[palette]
  blue = '#89B4FA'
  closer = 'p:os'
  lavender = '#B4BEFE'
  os = '#ACB0BE'
  pink = '#F5C2E7'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:blue'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    #template = '{{ .HEAD }} '
    template = '{{ .HEAD }} {{ .BranchStatus }}{{ if .Working.Changed }} ({{ .Working.String }}){{ end }}{{ if and .Working.Changed .Staging.Changed }}  {{ end }}{{ if .Staging.Changed }}  ({{ .Staging.String }}){{ end }}{{ if .StashCount }}  {{ .StashCount }} Stash{{ if gt .StashCount 1 }}es{{ end }}{{ end }}'
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      #fetch_status = false
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    template = ''
    foreground = 'p:closer'
    type = 'text'
    style = 'plain'
