version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ .UserName }}@{{ .HostName }} '
    foreground = '#ffffff'
    background = '#07585c'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = '  {{ .Path }} '
    foreground = '#ffffff'
    background = '#3e9022'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }} '
    foreground = '#ffffff'
    background = '#de076f'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ .Icon }}{{ if ne .Status "stopped" }}{{ .Artist }} - {{ .Track }}{{ end }} '
    foreground = '#ffffff'
    background = '#491545'
    type = 'spotify'
    style = 'plain'

    [blocks.segments.properties]
      paused_icon = ' '
      playing_icon = ' '
      stopped_icon = ' '
      track_separator = ' - '

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  '
    foreground = '#ffffff'
    background = '#491515'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
